package com.example.tierraburritoapp.common

object Constantes {

    const val DIRECCION_INVALIDA = "La dirección del pedido es inválida"
    const val PEDIDO_NULO = "El pedido seleccionado es nulo"
    const val INTRODUZCA_DIRECCION = "Introduzca la dirección de entrega"
    const val PEDIDO_SELECCIONADO = "Pedido seleccionado"
    const val PEDIDOS_REPARTIDOS = "Pedidos repartidos"
    const val PEDIDO_ACEPTADO = "Pedido aceptado"
    const val SELECCION_PEDIDOS = "Selección de pedidos"
    const val BEARER = "Bearer "
    const val ACCESS_TOKEN = "ACCESS_TOKEN"
    const val ANADIR = "Añadir"
    const val ANADIR_PLATO_A_PEDIDO = "Añadir plato al pedido"
    const val AUTHORIZATION = "Authorization"
    const val CLIENTE = "CLIENTE"
    const val CONTRASENA = "Contraseña"
    const val CORREO_CONTRASENA_INCORRECTOS = "Correo o contraseña incorrectos"
    const val CORREO_ELECTRONICO = "Correo electrónico"
    const val CONFIRMAR_PEDIDO = "Confirmar pedido"
    const val DATASTORE = "datastore"
    const val DETALLE_PLATO = "DetallePlato"
    const val DIRECCION = "Dirección"
    const val ERROR_DESCONOCIDO = "Hubo un fallo inesperado"
    const val ERROR_INICIANDO_SESION = "Error iniciando sesión"
    const val ERROR_MAPEANDO = "Error mapeando objeto"
    const val ELIMINAR = "Eliminar"
    const val ESTADO = "Estado: "
    const val EXTRAS = "Extras"
    const val FOTO_PLATO = "Imagen del plato"
    const val FOTO_INGREDIENTE = "Foto ingrediente"
    const val ID = "Id"
    const val INGREDIENTES = "Ingredientes"
    const val INICIAR_SESION = "Iniciar sesión"
    const val LISTA_PLATOS = "ListaPlatos"
    const val LOCALIZED_DESCRIPTION = "Localized Description"
    const val LOADING_INDICATOR = "LoadingIndicator"
    const val LOGIN = "Login"
    const val MESSAGE = "message"
    const val MENSAJE = "mensaje"
    const val MIS_PEDIDOS = "Mis pedidos"
    const val NOMBRE = "Nombre"
    const val PEDIDO_ACTUAL = "Pedido actual"
    const val PEDIDO_REALIZADO = "Pedido realizado"
    const val PLATOS = "Platos"
    const val PLATO_ANADIDO_A_PEDIDO = "Plato añadido a pedido"
    const val PRECIO = "Precio"
    const val REFRESH_TOKEN = "REFRESH_TOKEN"
    const val REGISTRARSE = "Registrarse"
    const val REPARTIDOR = "REPARTIDOR"
    const val RutaFoto = "RutaFoto"
    const val SESION_INICIADA = "Sesión iniciada"
    const val SIMBOLO_EURO = "€"
    const val TOTAL = "Total: "
    const val TOKEN_CADUCADO = "Token caducado"
    const val USUARIO_ANADIDO = "Usuario añadido con éxito"
}
